#!/bin/bash
#SBATCH --job-name=omnifed
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --time=02:00:00
#SBATCH --signal=B:USR1@180
#SBATCH -C nvme
#SBATCH --ntasks=2
#SBATCH --account=GEN150
#SBATCH --partition=batch
#SBATCH -o /autofs/nccs-svm1_home2/sabiha/OmniFed/outputs/2026-04-08/test_fedavg_centralized_torchdist/slurm-%j.out
#SBATCH -e /autofs/nccs-svm1_home2/sabiha/OmniFed/outputs/2026-04-08/test_fedavg_centralized_torchdist/slurm-%j.err
#SBATCH --chdir=/autofs/nccs-svm1_home2/sabiha/OmniFed
#SBATCH --gres=gpu:1
#SBATCH --gpus-per-task=1
set -euo pipefail
export PYTHONPATH="${PYTHONPATH:-}:/autofs/nccs-svm1_home2/sabiha/OmniFed"
export PYTHONUNBUFFERED=1
export HYDRA_FULL_ERROR=1
export OMNIFED_DEBUG=${OMNIFED_DEBUG:-0}

module load PrgEnv-gnu/8.6.0
module load rocm/6.4.1
module load craype-accel-amd-gfx90a
export OMNIFED_DATA_DIR="/ccs/home/sabiha/OmniFed/datasets"
echo "[setup] OMNIFED_DATA_DIR=$OMNIFED_DATA_DIR"

export ENV_TARBALL="/ccs/home/sabiha/omnifed.tar.gz"
export ENV_ROOT="/mnt/bb/${USER}/omnifed_env"
export ENV_BASE="/mnt/bb/${USER}"
export ENV_COPY="/mnt/bb/${USER}/omnifed.tar.gz"

echo "[setup] hostname=$(hostname)"
echo "[setup] ENV_TARBALL=$ENV_TARBALL"
echo "[setup] ENV_BASE=$ENV_BASE"
echo "[setup] ENV_ROOT=$ENV_ROOT"
echo "[setup] ENV_COPY=$ENV_COPY"
ls -lh "$ENV_TARBALL"

echo "[setup] Broadcasting packed env to compute nodes"
srun --ntasks-per-node=1 bash -lc 'mkdir -p "$ENV_BASE"'
sbcast -pf "$ENV_TARBALL" "$ENV_COPY"
echo "[setup] sbcast finished"
srun --ntasks-per-node=1 bash -lc 'ls -lh "$ENV_COPY"'

echo "[setup] starting unpack..."
srun --ntasks-per-node=1 bash -lc 'mkdir -p "$ENV_ROOT" && tar -xzf "$ENV_COPY" -C "$ENV_ROOT"'
echo "[setup] unpack finished"
srun --ntasks-per-node=1 bash -lc 'ls -lh "$ENV_ROOT/bin/python"'
srun --ntasks-per-node=1 bash -lc 'ls -lh "$ENV_ROOT/bin/activate"'

if [ ! -f "$ENV_ROOT/bin/python" ]; then echo "[setup] ERROR: python missing at $ENV_ROOT/bin/python"; exit 1; fi
if [ ! -f "$ENV_ROOT/bin/activate" ]; then echo "[setup] ERROR: activate missing at $ENV_ROOT/bin/activate"; exit 1; fi

echo "[setup] running conda-unpack..."
srun --ntasks-per-node=1 bash -lc 'source "$ENV_ROOT/bin/activate" && conda-unpack'
echo "[setup] conda-unpack finished"

export PYEXE="$ENV_ROOT/bin/python"
echo "[setup] PYEXE=$PYEXE"
"$PYEXE" --version

echo "SLURM_JOB_ID=$SLURM_JOB_ID"
echo "SLURM_NODELIST=$SLURM_NODELIST"
echo "Running on $(hostname)"
echo "PYTHONPATH=$PYTHONPATH"
echo "Requested PYEXE=python"

srun --ntasks-per-node=1 bash -lc 'mkdir -p /autofs/nccs-svm1_home2/sabiha/OmniFed/outputs'

export OMNIFED_CFG_B64="ewogICJjZmciOiB7CiAgICAidG9wb2xvZ3kiOiB7CiAgICAgICJfdGFyZ2V0XyI6ICJzcmMub21uaWZlZC50b3BvbG9neS5DZW50cmFsaXplZFRvcG9sb2d5IiwKICAgICAgIm51bV9jbGllbnRzIjogMSwKICAgICAgImxvY2FsX2NvbW0iOiB7CiAgICAgICAgIl90YXJnZXRfIjogInNyYy5vbW5pZmVkLmNvbW11bmljYXRvci5Ub3JjaERpc3RDb21tdW5pY2F0b3IiLAogICAgICAgICJtYXN0ZXJfYWRkciI6ICIxMjcuMC4wLjEiLAogICAgICAgICJtYXN0ZXJfcG9ydCI6ICIyOTUwMCIKICAgICAgfSwKICAgICAgIm92ZXJyaWRlcyI6IHsKICAgICAgICAiMCI6IHsKICAgICAgICAgICJkYXRhbW9kdWxlIjogewogICAgICAgICAgICAidHJhaW4iOiBudWxsCiAgICAgICAgICB9CiAgICAgICAgfQogICAgICB9CiAgICB9LAogICAgImFsZ29yaXRobSI6IHsKICAgICAgInNjaGVkdWxlcyI6IHsKICAgICAgICAiYWdncmVnYXRpb24iOiB7CiAgICAgICAgICAiX3RhcmdldF8iOiAic3JjLm9tbmlmZWQuYWxnb3JpdGhtLkFnZ3JlZ2F0aW9uVHJpZ2dlcnMiLAogICAgICAgICAgInJvdW5kX2VuZCI6IHsKICAgICAgICAgICAgIl90YXJnZXRfIjogInNyYy5vbW5pZmVkLmFsZ29yaXRobS5fc2NoZWR1bGVzLlRyaWdnZXIiLAogICAgICAgICAgICAiZW5hYmxlZCI6IHRydWUsCiAgICAgICAgICAgICJldmVyeSI6IDEKICAgICAgICAgIH0sCiAgICAgICAgICAiZXBvY2hfZW5kIjogewogICAgICAgICAgICAiX3RhcmdldF8iOiAic3JjLm9tbmlmZWQuYWxnb3JpdGhtLl9zY2hlZHVsZXMuVHJpZ2dlciIsCiAgICAgICAgICAgICJlbmFibGVkIjogZmFsc2UKICAgICAgICAgIH0sCiAgICAgICAgICAiYmF0Y2hfZW5kIjogewogICAgICAgICAgICAiX3RhcmdldF8iOiAic3JjLm9tbmlmZWQuYWxnb3JpdGhtLl9zY2hlZHVsZXMuVHJpZ2dlciIsCiAgICAgICAgICAgICJlbmFibGVkIjogZmFsc2UKICAgICAgICAgIH0KICAgICAgICB9LAogICAgICAgICJldmFsdWF0aW9uIjogewogICAgICAgICAgIl90YXJnZXRfIjogInNyYy5vbW5pZmVkLmFsZ29yaXRobS5FdmFsdWF0aW9uVHJpZ2dlcnMiLAogICAgICAgICAgImV4cGVyaW1lbnRfc3RhcnQiOiB7CiAgICAgICAgICAgICJfdGFyZ2V0XyI6ICJzcmMub21uaWZlZC5hbGdvcml0aG0uX3NjaGVkdWxlcy5UcmlnZ2VyIiwKICAgICAgICAgICAgImVuYWJsZWQiOiB0cnVlCiAgICAgICAgICB9LAogICAgICAgICAgImV4cGVyaW1lbnRfZW5kIjogewogICAgICAgICAgICAiX3RhcmdldF8iOiAic3JjLm9tbmlmZWQuYWxnb3JpdGhtLl9zY2hlZHVsZXMuVHJpZ2dlciIsCiAgICAgICAgICAgICJlbmFibGVkIjogdHJ1ZQogICAgICAgICAgfSwKICAgICAgICAgICJwcmVfYWdncmVnYXRpb24iOiB7CiAgICAgICAgICAgICJfdGFyZ2V0XyI6ICJzcmMub21uaWZlZC5hbGdvcml0aG0uX3NjaGVkdWxlcy5UcmlnZ2VyIiwKICAgICAgICAgICAgImVuYWJsZWQiOiBmYWxzZQogICAgICAgICAgfSwKICAgICAgICAgICJwb3N0X2FnZ3JlZ2F0aW9uIjogewogICAgICAgICAgICAiX3RhcmdldF8iOiAic3JjLm9tbmlmZWQuYWxnb3JpdGhtLl9zY2hlZHVsZXMuVHJpZ2dlciIsCiAgICAgICAgICAgICJlbmFibGVkIjogdHJ1ZQogICAgICAgICAgfQogICAgICAgIH0sCiAgICAgICAgIl90YXJnZXRfIjogInNyYy5vbW5pZmVkLmFsZ29yaXRobS5FeGVjdXRpb25TY2hlZHVsZXMiCiAgICAgIH0sCiAgICAgICJfdGFyZ2V0XyI6ICJzcmMub21uaWZlZC5hbGdvcml0aG0uRmVkQXZnIiwKICAgICAgImxvY2FsX2xyIjogMC4wMDUsCiAgICAgICJtYXhfZXBvY2hzX3Blcl9yb3VuZCI6IDMKICAgIH0sCiAgICAibW9kZWwiOiB7CiAgICAgICJfdGFyZ2V0XyI6ICJzcmMub21uaWZlZC5tb2RlbC5Db21wb3NhYmxlTW9kZWwiLAogICAgICAiYmFja2JvbmUiOiB7CiAgICAgICAgIl90YXJnZXRfIjogInNyYy5vbW5pZmVkLm1vZGVsLlNpbXBsZUNOTkJhY2tib25lIiwKICAgICAgICAiaW5fY2hhbm5lbHMiOiAxLAogICAgICAgICJoaWRkZW5fY2hhbm5lbHMiOiBbCiAgICAgICAgICAzMiwKICAgICAgICAgIDY0CiAgICAgICAgXSwKICAgICAgICAib3V0X2NoYW5uZWxzIjogMTI4LAogICAgICAgICJrZXJuZWxfc2l6ZXMiOiAzLAogICAgICAgICJwYWRkaW5ncyI6IDEKICAgICAgfSwKICAgICAgImhlYWQiOiB7CiAgICAgICAgIl90YXJnZXRfIjogInNyYy5vbW5pZmVkLm1vZGVsLkNsYXNzaWZpY2F0aW9uSGVhZCIsCiAgICAgICAgImluX2NoYW5uZWxzIjogMTI4LAogICAgICAgICJudW1fY2xhc3NlcyI6IDEwCiAgICAgIH0KICAgIH0sCiAgICAiZGF0YW1vZHVsZSI6IHsKICAgICAgInRyYWluIjogewogICAgICAgICJfdGFyZ2V0XyI6ICJ0b3JjaC51dGlscy5kYXRhLkRhdGFMb2FkZXIiLAogICAgICAgICJkYXRhc2V0IjogewogICAgICAgICAgIl90YXJnZXRfIjogInRvcmNodmlzaW9uLmRhdGFzZXRzLk1OSVNUIiwKICAgICAgICAgICJyb290IjogIi9jY3MvaG9tZS9zYWJpaGEvT21uaUZlZC9kYXRhc2V0cy90b3JjaHZpc2lvbi1tbmlzdCIsCiAgICAgICAgICAidHJhaW4iOiB0cnVlLAogICAgICAgICAgImRvd25sb2FkIjogdHJ1ZSwKICAgICAgICAgICJ0cmFuc2Zvcm0iOiB7CiAgICAgICAgICAgICJfdGFyZ2V0XyI6ICJ0b3JjaHZpc2lvbi50cmFuc2Zvcm1zLkNvbXBvc2UiLAogICAgICAgICAgICAidHJhbnNmb3JtcyI6IFsKICAgICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAiX3RhcmdldF8iOiAidG9yY2h2aXNpb24udHJhbnNmb3Jtcy5Ub1RlbnNvciIKICAgICAgICAgICAgICB9LAogICAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgICJfdGFyZ2V0XyI6ICJ0b3JjaHZpc2lvbi50cmFuc2Zvcm1zLk5vcm1hbGl6ZSIsCiAgICAgICAgICAgICAgICAibWVhbiI6IFsKICAgICAgICAgICAgICAgICAgMC4xMzA3CiAgICAgICAgICAgICAgICBdLAogICAgICAgICAgICAgICAgInN0ZCI6IFsKICAgICAgICAgICAgICAgICAgMC4zMDgxCiAgICAgICAgICAgICAgICBdCiAgICAgICAgICAgICAgfQogICAgICAgICAgICBdCiAgICAgICAgICB9CiAgICAgICAgfSwKICAgICAgICAiYmF0Y2hfc2l6ZSI6IDEyOCwKICAgICAgICAic2h1ZmZsZSI6IHRydWUsCiAgICAgICAgIm51bV93b3JrZXJzIjogMiwKICAgICAgICAicGluX21lbW9yeSI6IHRydWUsCiAgICAgICAgInBlcnNpc3RlbnRfd29ya2VycyI6IHRydWUKICAgICAgfSwKICAgICAgImV2YWwiOiB7CiAgICAgICAgIl90YXJnZXRfIjogInRvcmNoLnV0aWxzLmRhdGEuRGF0YUxvYWRlciIsCiAgICAgICAgImRhdGFzZXQiOiB7CiAgICAgICAgICAiX3RhcmdldF8iOiAidG9yY2h2aXNpb24uZGF0YXNldHMuTU5JU1QiLAogICAgICAgICAgInJvb3QiOiAiL2Njcy9ob21lL3NhYmloYS9PbW5pRmVkL2RhdGFzZXRzL3RvcmNodmlzaW9uLW1uaXN0IiwKICAgICAgICAgICJ0cmFpbiI6IGZhbHNlLAogICAgICAgICAgImRvd25sb2FkIjogdHJ1ZSwKICAgICAgICAgICJ0cmFuc2Zvcm0iOiB7CiAgICAgICAgICAgICJfdGFyZ2V0XyI6ICJ0b3JjaHZpc2lvbi50cmFuc2Zvcm1zLkNvbXBvc2UiLAogICAgICAgICAgICAidHJhbnNmb3JtcyI6IFsKICAgICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAiX3RhcmdldF8iOiAidG9yY2h2aXNpb24udHJhbnNmb3Jtcy5Ub1RlbnNvciIKICAgICAgICAgICAgICB9LAogICAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgICJfdGFyZ2V0XyI6ICJ0b3JjaHZpc2lvbi50cmFuc2Zvcm1zLk5vcm1hbGl6ZSIsCiAgICAgICAgICAgICAgICAibWVhbiI6IFsKICAgICAgICAgICAgICAgICAgMC4xMzA3CiAgICAgICAgICAgICAgICBdLAogICAgICAgICAgICAgICAgInN0ZCI6IFsKICAgICAgICAgICAgICAgICAgMC4zMDgxCiAgICAgICAgICAgICAgICBdCiAgICAgICAgICAgICAgfQogICAgICAgICAgICBdCiAgICAgICAgICB9CiAgICAgICAgfSwKICAgICAgICAiYmF0Y2hfc2l6ZSI6IDEyOCwKICAgICAgICAic2h1ZmZsZSI6IGZhbHNlLAogICAgICAgICJudW1fd29ya2VycyI6IDIsCiAgICAgICAgInBpbl9tZW1vcnkiOiB0cnVlLAogICAgICAgICJwZXJzaXN0ZW50X3dvcmtlcnMiOiB0cnVlCiAgICAgIH0sCiAgICAgICJfdGFyZ2V0XyI6ICJzcmMub21uaWZlZC5kYXRhLkRhdGFNb2R1bGUiCiAgICB9LAogICAgImdsb2JhbF9yb3VuZHMiOiAyLAogICAgIm92ZXJ3cml0ZSI6IGZhbHNlLAogICAgInJheSI6IHsKICAgICAgImFkZHJlc3MiOiBudWxsLAogICAgICAibnVtX2NwdXMiOiBudWxsLAogICAgICAibnVtX2dwdXMiOiBudWxsLAogICAgICAicmVzb3VyY2VzIjoge30sCiAgICAgICJvYmplY3Rfc3RvcmVfbWVtb3J5IjogbnVsbCwKICAgICAgImxvZ190b19kcml2ZXIiOiB0cnVlLAogICAgICAiaW5jbHVkZV9kYXNoYm9hcmQiOiBudWxsLAogICAgICAiZGFzaGJvYXJkX2hvc3QiOiAiMTI3LjAuMC4xIiwKICAgICAgImRhc2hib2FyZF9wb3J0IjogbnVsbCwKICAgICAgImlnbm9yZV9yZWluaXRfZXJyb3IiOiB0cnVlLAogICAgICAibmFtZXNwYWNlIjogbnVsbCwKICAgICAgInJ1bnRpbWVfZW52Ijoge30KICAgIH0sCiAgICAic2x1cm0iOiB7CiAgICAgICJlbmFibGVkIjogZmFsc2UsCiAgICAgICJhY2NvdW50IjogIkdFTjE1MCIsCiAgICAgICJwYXJ0aXRpb24iOiAiYmF0Y2giLAogICAgICAicW9zIjogbnVsbCwKICAgICAgInRpbWUiOiAiMDI6MDA6MDAiLAogICAgICAibm9kZXMiOiAyLAogICAgICAibnRhc2tzX3Blcl9ub2RlIjogMSwKICAgICAgImNwdXNfcGVyX3Rhc2siOiA4LAogICAgICAiZ3B1c19wZXJfbm9kZSI6IDEsCiAgICAgICJncHVzX3Blcl90YXNrIjogMSwKICAgICAgImdyZXMiOiAiZ3B1OjEiLAogICAgICAiam9iX25hbWUiOiAib21uaWZlZCIsCiAgICAgICJjb25zdHJhaW50IjogbnVsbCwKICAgICAgInJlc2VydmF0aW9uIjogbnVsbCwKICAgICAgInNldHVwX2xpbmVzIjogWwogICAgICAgICJtb2R1bGUgbG9hZCBjcmF5LXB5dGhvbiB8fCB0cnVlIiwKICAgICAgICAiZXhwb3J0IE9NUF9OVU1fVEhSRUFEUz04IgogICAgICBdLAogICAgICAiY2hlY2twb2ludF9kaXIiOiBudWxsLAogICAgICAicHJlZW1wdF9zaWduYWwiOiAiVVNSMSIsCiAgICAgICJwcmVlbXB0X25vdGljZV9zZWMiOiAxODAsCiAgICAgICJyZXN1bWVfZnJvbSI6IG51bGwKICAgIH0sCiAgICAiZW5naW5lIjogewogICAgICAibW9kZSI6ICJzbHVybSIKICAgIH0KICB9LAogICJoeWRyYV9vdXRwdXRfZGlyIjogIi9hdXRvZnMvbmNjcy1zdm0xX2hvbWUyL3NhYmloYS9PbW5pRmVkL291dHB1dHMvMjAyNi0wNC0wOC90ZXN0X2ZlZGF2Z19jZW50cmFsaXplZF90b3JjaGRpc3QiLAogICJzbHVybV9jaGVja3BvaW50X2RpciI6ICIvYXV0b2ZzL25jY3Mtc3ZtMV9ob21lMi9zYWJpaGEvT21uaUZlZC9vdXRwdXRzLzIwMjYtMDQtMDgvdGVzdF9mZWRhdmdfY2VudHJhbGl6ZWRfdG9yY2hkaXN0L2VuZ2luZS9ja3B0Igp9"
srun --ntasks-per-node=1 bash -lc 'echo "$OMNIFED_CFG_B64" | base64 -d > /autofs/nccs-svm1_home2/sabiha/OmniFed/outputs/engine_frozen.json'
srun --ntasks-per-node=1 bash -lc 'echo "[$(hostname)] wrote /autofs/nccs-svm1_home2/sabiha/OmniFed/outputs/engine_frozen.json; size=$(stat -c%s /autofs/nccs-svm1_home2/sabiha/OmniFed/outputs/engine_frozen.json) bytes"'

set -x
srun --export=ALL bash -lc 'if [ -n "${ROCR_VISIBLE_DEVICES:-}" ] && [ -z "${HIP_VISIBLE_DEVICES:-}" ]; then export HIP_VISIBLE_DEVICES="$ROCR_VISIBLE_DEVICES"; fi; unset ROCR_VISIBLE_DEVICES; echo "HIP_VISIBLE_DEVICES=${HIP_VISIBLE_DEVICES:-<unset>}"; echo "ROCR_VISIBLE_DEVICES=${ROCR_VISIBLE_DEVICES:-<unset>}"; echo "Using worker python: ${PYEXE:-python}"; ${PYEXE:-python} -u -m src.omnifed.slurm_worker --cfg-json /autofs/nccs-svm1_home2/sabiha/OmniFed/outputs/engine_frozen.json'
set +x
