#!/bin/bash
#SBATCH --job-name=omnifed
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=7
#SBATCH --cpus-per-task=8
#SBATCH --time=02:00:00
#SBATCH --signal=B:USR1@180
#SBATCH -C nvme
#SBATCH --ntasks=28
#SBATCH --account=GEN150
#SBATCH --partition=batch
#SBATCH -o /autofs/nccs-svm1_home2/sabiha/OmniFed/outputs/2026-04-21/test_fedavg_centralized_torchdist/slurm-%j.out
#SBATCH -e /autofs/nccs-svm1_home2/sabiha/OmniFed/outputs/2026-04-21/test_fedavg_centralized_torchdist/slurm-%j.err
#SBATCH --chdir=/autofs/nccs-svm1_home2/sabiha/OmniFed
#SBATCH --gpus-per-node=7
#SBATCH --gpus-per-task=1
set -euo pipefail
export PYTHONPATH="${PYTHONPATH:-}:/autofs/nccs-svm1_home2/sabiha/OmniFed"
export PYTHONUNBUFFERED=1
export HYDRA_FULL_ERROR=1
export OMNIFED_DEBUG=${OMNIFED_DEBUG:-0}

module load PrgEnv-gnu/8.6.0
module load rocm/6.4.1
module load craype-accel-amd-gfx90a
export OMNIFED_DATA_DIR="/ccs/home/sabiha/OmniFed/datasets"
echo "[setup] OMNIFED_DATA_DIR=$OMNIFED_DATA_DIR"

export ENV_TARBALL="/ccs/home/sabiha/omnifed.tar.gz"
export ENV_ROOT="/mnt/bb/${USER}/omnifed_env"
export ENV_BASE="/mnt/bb/${USER}"
export ENV_COPY="/mnt/bb/${USER}/omnifed.tar.gz"
export MIOPEN_USER_DB_PATH="/mnt/bb/${USER}/miopen-cache"
export MIOPEN_CUSTOM_CACHE_DIR="/mnt/bb/${USER}/miopen-cache"
export MIOPEN_FIND_MODE=1
srun -N "$SLURM_JOB_NUM_NODES" -n "$SLURM_JOB_NUM_NODES" --ntasks-per-node=1 bash -lc 'mkdir -p "$MIOPEN_USER_DB_PATH"'
echo "[setup] MIOPEN_USER_DB_PATH=$MIOPEN_USER_DB_PATH"

echo "[setup] hostname=$(hostname)"
echo "[setup] ENV_TARBALL=$ENV_TARBALL"
echo "[setup] ENV_BASE=$ENV_BASE"
echo "[setup] ENV_ROOT=$ENV_ROOT"
echo "[setup] ENV_COPY=$ENV_COPY"
ls -lh "$ENV_TARBALL"

echo "[setup] Broadcasting packed env to compute nodes"
srun -N "$SLURM_JOB_NUM_NODES" -n "$SLURM_JOB_NUM_NODES" --ntasks-per-node=1 bash -lc 'mkdir -p "$ENV_BASE"'
sbcast -pf "$ENV_TARBALL" "$ENV_COPY"
echo "[setup] sbcast finished"
srun -N "$SLURM_JOB_NUM_NODES" -n "$SLURM_JOB_NUM_NODES" --ntasks-per-node=1 bash -lc 'ls -lh "$ENV_COPY"'

echo "[setup] starting unpack..."
srun -N "$SLURM_JOB_NUM_NODES" -n "$SLURM_JOB_NUM_NODES" --ntasks-per-node=1 bash -lc 'rm -rf "$ENV_ROOT" && mkdir -p "$ENV_ROOT" && tar -xzf "$ENV_COPY" -C "$ENV_ROOT"'
echo "[setup] unpack finished"
srun -N "$SLURM_JOB_NUM_NODES" -n "$SLURM_JOB_NUM_NODES" --ntasks-per-node=1 bash -lc 'ls -lh "$ENV_ROOT/bin/python"'
srun -N "$SLURM_JOB_NUM_NODES" -n "$SLURM_JOB_NUM_NODES" --ntasks-per-node=1 bash -lc 'ls -lh "$ENV_ROOT/bin/activate"'

if [ ! -f "$ENV_ROOT/bin/python" ]; then echo "[setup] ERROR: python missing at $ENV_ROOT/bin/python"; exit 1; fi
if [ ! -f "$ENV_ROOT/bin/activate" ]; then echo "[setup] ERROR: activate missing at $ENV_ROOT/bin/activate"; exit 1; fi

echo "[setup] running conda-unpack..."
srun -N "$SLURM_JOB_NUM_NODES" -n "$SLURM_JOB_NUM_NODES" --ntasks-per-node=1 bash -lc 'source "$ENV_ROOT/bin/activate" && conda-unpack'
echo "[setup] conda-unpack finished"

export PYEXE="$ENV_ROOT/bin/python"
echo "[setup] PYEXE=$PYEXE"
"$PYEXE" --version

echo "SLURM_JOB_ID=$SLURM_JOB_ID"
echo "SLURM_NODELIST=$SLURM_NODELIST"
echo "Running on $(hostname)"
echo "PYTHONPATH=$PYTHONPATH"
echo "Requested PYEXE=python"

srun -N "$SLURM_JOB_NUM_NODES" -n "$SLURM_JOB_NUM_NODES" --ntasks-per-node=1 bash -lc 'mkdir -p /autofs/nccs-svm1_home2/sabiha/OmniFed/outputs'

export OMNIFED_CFG_B64="ewogICJjZmciOiB7CiAgICAidG9wb2xvZ3kiOiB7CiAgICAgICJfdGFyZ2V0XyI6ICJzcmMub21uaWZlZC50b3BvbG9neS5DZW50cmFsaXplZFRvcG9sb2d5IiwKICAgICAgIm51bV9jbGllbnRzIjogMjcsCiAgICAgICJsb2NhbF9jb21tIjogewogICAgICAgICJfdGFyZ2V0XyI6ICJzcmMub21uaWZlZC5jb21tdW5pY2F0b3IuVG9yY2hEaXN0Q29tbXVuaWNhdG9yIiwKICAgICAgICAiYmFja2VuZCI6ICJuY2NsIiwKICAgICAgICAibWFzdGVyX2FkZHIiOiAiMTI3LjAuMC4xIiwKICAgICAgICAibWFzdGVyX3BvcnQiOiAiMjk1MDAiCiAgICAgIH0sCiAgICAgICJvdmVycmlkZXMiOiB7CiAgICAgICAgIjAiOiB7CiAgICAgICAgICAiZGF0YW1vZHVsZSI6IHsKICAgICAgICAgICAgInRyYWluIjogbnVsbAogICAgICAgICAgfQogICAgICAgIH0KICAgICAgfQogICAgfSwKICAgICJhbGdvcml0aG0iOiB7CiAgICAgICJzY2hlZHVsZXMiOiB7CiAgICAgICAgImFnZ3JlZ2F0aW9uIjogewogICAgICAgICAgIl90YXJnZXRfIjogInNyYy5vbW5pZmVkLmFsZ29yaXRobS5BZ2dyZWdhdGlvblRyaWdnZXJzIiwKICAgICAgICAgICJyb3VuZF9lbmQiOiB7CiAgICAgICAgICAgICJfdGFyZ2V0XyI6ICJzcmMub21uaWZlZC5hbGdvcml0aG0uX3NjaGVkdWxlcy5UcmlnZ2VyIiwKICAgICAgICAgICAgImVuYWJsZWQiOiB0cnVlLAogICAgICAgICAgICAiZXZlcnkiOiAxCiAgICAgICAgICB9LAogICAgICAgICAgImVwb2NoX2VuZCI6IHsKICAgICAgICAgICAgIl90YXJnZXRfIjogInNyYy5vbW5pZmVkLmFsZ29yaXRobS5fc2NoZWR1bGVzLlRyaWdnZXIiLAogICAgICAgICAgICAiZW5hYmxlZCI6IGZhbHNlCiAgICAgICAgICB9LAogICAgICAgICAgImJhdGNoX2VuZCI6IHsKICAgICAgICAgICAgIl90YXJnZXRfIjogInNyYy5vbW5pZmVkLmFsZ29yaXRobS5fc2NoZWR1bGVzLlRyaWdnZXIiLAogICAgICAgICAgICAiZW5hYmxlZCI6IGZhbHNlCiAgICAgICAgICB9CiAgICAgICAgfSwKICAgICAgICAiZXZhbHVhdGlvbiI6IHsKICAgICAgICAgICJfdGFyZ2V0XyI6ICJzcmMub21uaWZlZC5hbGdvcml0aG0uRXZhbHVhdGlvblRyaWdnZXJzIiwKICAgICAgICAgICJleHBlcmltZW50X3N0YXJ0IjogewogICAgICAgICAgICAiX3RhcmdldF8iOiAic3JjLm9tbmlmZWQuYWxnb3JpdGhtLl9zY2hlZHVsZXMuVHJpZ2dlciIsCiAgICAgICAgICAgICJlbmFibGVkIjogdHJ1ZQogICAgICAgICAgfSwKICAgICAgICAgICJleHBlcmltZW50X2VuZCI6IHsKICAgICAgICAgICAgIl90YXJnZXRfIjogInNyYy5vbW5pZmVkLmFsZ29yaXRobS5fc2NoZWR1bGVzLlRyaWdnZXIiLAogICAgICAgICAgICAiZW5hYmxlZCI6IHRydWUKICAgICAgICAgIH0sCiAgICAgICAgICAicHJlX2FnZ3JlZ2F0aW9uIjogewogICAgICAgICAgICAiX3RhcmdldF8iOiAic3JjLm9tbmlmZWQuYWxnb3JpdGhtLl9zY2hlZHVsZXMuVHJpZ2dlciIsCiAgICAgICAgICAgICJlbmFibGVkIjogZmFsc2UKICAgICAgICAgIH0sCiAgICAgICAgICAicG9zdF9hZ2dyZWdhdGlvbiI6IHsKICAgICAgICAgICAgIl90YXJnZXRfIjogInNyYy5vbW5pZmVkLmFsZ29yaXRobS5fc2NoZWR1bGVzLlRyaWdnZXIiLAogICAgICAgICAgICAiZW5hYmxlZCI6IHRydWUKICAgICAgICAgIH0KICAgICAgICB9LAogICAgICAgICJfdGFyZ2V0XyI6ICJzcmMub21uaWZlZC5hbGdvcml0aG0uRXhlY3V0aW9uU2NoZWR1bGVzIgogICAgICB9LAogICAgICAiX3RhcmdldF8iOiAic3JjLm9tbmlmZWQuYWxnb3JpdGhtLkZlZEF2ZyIsCiAgICAgICJsb2NhbF9sciI6IDAuMDA1LAogICAgICAibWF4X2Vwb2Noc19wZXJfcm91bmQiOiAzCiAgICB9LAogICAgIm1vZGVsIjogewogICAgICAiX3RhcmdldF8iOiAic3JjLm9tbmlmZWQubW9kZWwuQ29tcG9zYWJsZU1vZGVsIiwKICAgICAgImJhY2tib25lIjogewogICAgICAgICJfdGFyZ2V0XyI6ICJzcmMub21uaWZlZC5tb2RlbC5TaW1wbGVDTk5CYWNrYm9uZSIsCiAgICAgICAgImluX2NoYW5uZWxzIjogMSwKICAgICAgICAiaGlkZGVuX2NoYW5uZWxzIjogWwogICAgICAgICAgMzIsCiAgICAgICAgICA2NAogICAgICAgIF0sCiAgICAgICAgIm91dF9jaGFubmVscyI6IDEyOCwKICAgICAgICAia2VybmVsX3NpemVzIjogMywKICAgICAgICAicGFkZGluZ3MiOiAxCiAgICAgIH0sCiAgICAgICJoZWFkIjogewogICAgICAgICJfdGFyZ2V0XyI6ICJzcmMub21uaWZlZC5tb2RlbC5DbGFzc2lmaWNhdGlvbkhlYWQiLAogICAgICAgICJpbl9jaGFubmVscyI6IDEyOCwKICAgICAgICAibnVtX2NsYXNzZXMiOiAxMAogICAgICB9CiAgICB9LAogICAgImRhdGFtb2R1bGUiOiB7CiAgICAgICJ0cmFpbiI6IHsKICAgICAgICAiX3RhcmdldF8iOiAidG9yY2gudXRpbHMuZGF0YS5EYXRhTG9hZGVyIiwKICAgICAgICAiZGF0YXNldCI6IHsKICAgICAgICAgICJfdGFyZ2V0XyI6ICJ0b3JjaHZpc2lvbi5kYXRhc2V0cy5NTklTVCIsCiAgICAgICAgICAicm9vdCI6ICIvY2NzL2hvbWUvc2FiaWhhL09tbmlGZWQvZGF0YXNldHMvdG9yY2h2aXNpb24tbW5pc3QiLAogICAgICAgICAgInRyYWluIjogdHJ1ZSwKICAgICAgICAgICJkb3dubG9hZCI6IHRydWUsCiAgICAgICAgICAidHJhbnNmb3JtIjogewogICAgICAgICAgICAiX3RhcmdldF8iOiAidG9yY2h2aXNpb24udHJhbnNmb3Jtcy5Db21wb3NlIiwKICAgICAgICAgICAgInRyYW5zZm9ybXMiOiBbCiAgICAgICAgICAgICAgewogICAgICAgICAgICAgICAgIl90YXJnZXRfIjogInRvcmNodmlzaW9uLnRyYW5zZm9ybXMuVG9UZW5zb3IiCiAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAiX3RhcmdldF8iOiAidG9yY2h2aXNpb24udHJhbnNmb3Jtcy5Ob3JtYWxpemUiLAogICAgICAgICAgICAgICAgIm1lYW4iOiBbCiAgICAgICAgICAgICAgICAgIDAuMTMwNwogICAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICAgICJzdGQiOiBbCiAgICAgICAgICAgICAgICAgIDAuMzA4MQogICAgICAgICAgICAgICAgXQogICAgICAgICAgICAgIH0KICAgICAgICAgICAgXQogICAgICAgICAgfQogICAgICAgIH0sCiAgICAgICAgImJhdGNoX3NpemUiOiAxMjgsCiAgICAgICAgInNodWZmbGUiOiB0cnVlLAogICAgICAgICJudW1fd29ya2VycyI6IDIsCiAgICAgICAgInBpbl9tZW1vcnkiOiB0cnVlLAogICAgICAgICJwZXJzaXN0ZW50X3dvcmtlcnMiOiB0cnVlCiAgICAgIH0sCiAgICAgICJldmFsIjogewogICAgICAgICJfdGFyZ2V0XyI6ICJ0b3JjaC51dGlscy5kYXRhLkRhdGFMb2FkZXIiLAogICAgICAgICJkYXRhc2V0IjogewogICAgICAgICAgIl90YXJnZXRfIjogInRvcmNodmlzaW9uLmRhdGFzZXRzLk1OSVNUIiwKICAgICAgICAgICJyb290IjogIi9jY3MvaG9tZS9zYWJpaGEvT21uaUZlZC9kYXRhc2V0cy90b3JjaHZpc2lvbi1tbmlzdCIsCiAgICAgICAgICAidHJhaW4iOiBmYWxzZSwKICAgICAgICAgICJkb3dubG9hZCI6IHRydWUsCiAgICAgICAgICAidHJhbnNmb3JtIjogewogICAgICAgICAgICAiX3RhcmdldF8iOiAidG9yY2h2aXNpb24udHJhbnNmb3Jtcy5Db21wb3NlIiwKICAgICAgICAgICAgInRyYW5zZm9ybXMiOiBbCiAgICAgICAgICAgICAgewogICAgICAgICAgICAgICAgIl90YXJnZXRfIjogInRvcmNodmlzaW9uLnRyYW5zZm9ybXMuVG9UZW5zb3IiCiAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAiX3RhcmdldF8iOiAidG9yY2h2aXNpb24udHJhbnNmb3Jtcy5Ob3JtYWxpemUiLAogICAgICAgICAgICAgICAgIm1lYW4iOiBbCiAgICAgICAgICAgICAgICAgIDAuMTMwNwogICAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICAgICJzdGQiOiBbCiAgICAgICAgICAgICAgICAgIDAuMzA4MQogICAgICAgICAgICAgICAgXQogICAgICAgICAgICAgIH0KICAgICAgICAgICAgXQogICAgICAgICAgfQogICAgICAgIH0sCiAgICAgICAgImJhdGNoX3NpemUiOiAxMjgsCiAgICAgICAgInNodWZmbGUiOiBmYWxzZSwKICAgICAgICAibnVtX3dvcmtlcnMiOiAyLAogICAgICAgICJwaW5fbWVtb3J5IjogdHJ1ZSwKICAgICAgICAicGVyc2lzdGVudF93b3JrZXJzIjogdHJ1ZQogICAgICB9LAogICAgICAiX3RhcmdldF8iOiAic3JjLm9tbmlmZWQuZGF0YS5EYXRhTW9kdWxlIgogICAgfSwKICAgICJnbG9iYWxfcm91bmRzIjogMiwKICAgICJvdmVyd3JpdGUiOiBmYWxzZSwKICAgICJyYXkiOiB7CiAgICAgICJhZGRyZXNzIjogbnVsbCwKICAgICAgIm51bV9jcHVzIjogbnVsbCwKICAgICAgIm51bV9ncHVzIjogbnVsbCwKICAgICAgInJlc291cmNlcyI6IHt9LAogICAgICAib2JqZWN0X3N0b3JlX21lbW9yeSI6IG51bGwsCiAgICAgICJsb2dfdG9fZHJpdmVyIjogdHJ1ZSwKICAgICAgImluY2x1ZGVfZGFzaGJvYXJkIjogbnVsbCwKICAgICAgImRhc2hib2FyZF9ob3N0IjogIjEyNy4wLjAuMSIsCiAgICAgICJkYXNoYm9hcmRfcG9ydCI6IG51bGwsCiAgICAgICJpZ25vcmVfcmVpbml0X2Vycm9yIjogdHJ1ZSwKICAgICAgIm5hbWVzcGFjZSI6IG51bGwsCiAgICAgICJydW50aW1lX2VudiI6IHt9CiAgICB9LAogICAgInNsdXJtIjogewogICAgICAiZW5hYmxlZCI6IGZhbHNlLAogICAgICAiYWNjb3VudCI6ICJHRU4xNTAiLAogICAgICAicGFydGl0aW9uIjogImJhdGNoIiwKICAgICAgInFvcyI6IG51bGwsCiAgICAgICJ0aW1lIjogIjAyOjAwOjAwIiwKICAgICAgIm5vZGVzIjogNCwKICAgICAgIm50YXNrc19wZXJfbm9kZSI6IDcsCiAgICAgICJjcHVzX3Blcl90YXNrIjogOCwKICAgICAgImdwdXNfcGVyX25vZGUiOiA3LAogICAgICAiZ3B1c19wZXJfdGFzayI6IDEsCiAgICAgICJncmVzIjogbnVsbCwKICAgICAgImpvYl9uYW1lIjogIm9tbmlmZWQiLAogICAgICAiY29uc3RyYWludCI6IG51bGwsCiAgICAgICJyZXNlcnZhdGlvbiI6IG51bGwsCiAgICAgICJzZXR1cF9saW5lcyI6IFsKICAgICAgICAibW9kdWxlIGxvYWQgY3JheS1weXRob24gfHwgdHJ1ZSIsCiAgICAgICAgImV4cG9ydCBPTVBfTlVNX1RIUkVBRFM9OCIKICAgICAgXSwKICAgICAgImNoZWNrcG9pbnRfZGlyIjogbnVsbCwKICAgICAgInByZWVtcHRfc2lnbmFsIjogIlVTUjEiLAogICAgICAicHJlZW1wdF9ub3RpY2Vfc2VjIjogMTgwLAogICAgICAicmVzdW1lX2Zyb20iOiBudWxsCiAgICB9LAogICAgImVuZ2luZSI6IHsKICAgICAgIm1vZGUiOiAic2x1cm0iCiAgICB9CiAgfSwKICAiaHlkcmFfb3V0cHV0X2RpciI6ICIvYXV0b2ZzL25jY3Mtc3ZtMV9ob21lMi9zYWJpaGEvT21uaUZlZC9vdXRwdXRzLzIwMjYtMDQtMjEvdGVzdF9mZWRhdmdfY2VudHJhbGl6ZWRfdG9yY2hkaXN0IiwKICAic2x1cm1fY2hlY2twb2ludF9kaXIiOiAiL2F1dG9mcy9uY2NzLXN2bTFfaG9tZTIvc2FiaWhhL09tbmlGZWQvb3V0cHV0cy8yMDI2LTA0LTIxL3Rlc3RfZmVkYXZnX2NlbnRyYWxpemVkX3RvcmNoZGlzdC9lbmdpbmUvY2twdCIKfQ=="
srun -N "$SLURM_JOB_NUM_NODES" -n "$SLURM_JOB_NUM_NODES" --ntasks-per-node=1 bash -lc 'echo "$OMNIFED_CFG_B64" | base64 -d > /autofs/nccs-svm1_home2/sabiha/OmniFed/outputs/engine_frozen.json'
srun -N "$SLURM_JOB_NUM_NODES" -n "$SLURM_JOB_NUM_NODES" --ntasks-per-node=1 bash -lc 'echo "[$(hostname)] wrote /autofs/nccs-svm1_home2/sabiha/OmniFed/outputs/engine_frozen.json; size=$(stat -c%s /autofs/nccs-svm1_home2/sabiha/OmniFed/outputs/engine_frozen.json) bytes"'

set -x
srun --export=ALL bash -lc 'if [ -n "${ROCR_VISIBLE_DEVICES:-}" ] && [ -z "${HIP_VISIBLE_DEVICES:-}" ]; then export HIP_VISIBLE_DEVICES="$ROCR_VISIBLE_DEVICES"; fi; unset ROCR_VISIBLE_DEVICES; echo "HIP_VISIBLE_DEVICES=${HIP_VISIBLE_DEVICES:-<unset>}"; echo "ROCR_VISIBLE_DEVICES=${ROCR_VISIBLE_DEVICES:-<unset>}"; echo "Using worker python: ${PYEXE:-python}"; ${PYEXE:-python} -u -m src.omnifed.slurm_worker --cfg-json /autofs/nccs-svm1_home2/sabiha/OmniFed/outputs/engine_frozen.json'
set +x
