# Copyright (c) 2025, Oak Ridge National Laboratory.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flora_grpc.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 0, "", "flora_grpc.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10\x66lora_grpc.proto\x12\nflora_grpc"v\n\x0bModelUpdate\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x14\n\x0cround_number\x18\x02 \x01(\x05\x12&\n\x06layers\x18\x03 \x03(\x0b\x32\x16.flora_grpc.LayerState\x12\x16\n\x0enumber_samples\x18\x04 \x01(\x05"K\n\nLayerState\x12\x12\n\nlayer_name\x18\x01 \x01(\t\x12\x14\n\x0cparam_update\x18\x02 \x03(\x02\x12\x13\n\x0bparam_shape\x18\x03 \x03(\x05"a\n\x0fModelParameters\x12\x14\n\x0cround_number\x18\x01 \x01(\x05\x12&\n\x06layers\x18\x02 \x03(\x0b\x32\x16.flora_grpc.LayerState\x12\x10\n\x08is_ready\x18\x03 \x01(\x08"h\n\x0eUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1a\n\x12\x63lients_registered\x18\x03 \x01(\x05\x12\x18\n\x10updates_received\x18\x04 \x01(\x05":\n\x0fGetModelRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x14\n\x0cround_number\x18\x02 \x01(\x05"\x1f\n\nClientInfo\x12\x11\n\tclient_id\x18\x01 \x01(\t"O\n\x14RegistrationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rtotal_clients\x18\x03 \x01(\x05\x32\xeb\x01\n\rCentralServer\x12\x41\n\nSendUpdate\x12\x17.flora_grpc.ModelUpdate\x1a\x1a.flora_grpc.UpdateResponse\x12K\n\x0fGetUpdatedModel\x12\x1b.flora_grpc.GetModelRequest\x1a\x1b.flora_grpc.ModelParameters\x12J\n\x0eRegisterClient\x12\x16.flora_grpc.ClientInfo\x1a .flora_grpc.RegistrationResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "flora_grpc_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_MODELUPDATE"]._serialized_start = 32
    _globals["_MODELUPDATE"]._serialized_end = 150
    _globals["_LAYERSTATE"]._serialized_start = 152
    _globals["_LAYERSTATE"]._serialized_end = 227
    _globals["_MODELPARAMETERS"]._serialized_start = 229
    _globals["_MODELPARAMETERS"]._serialized_end = 326
    _globals["_UPDATERESPONSE"]._serialized_start = 328
    _globals["_UPDATERESPONSE"]._serialized_end = 432
    _globals["_GETMODELREQUEST"]._serialized_start = 434
    _globals["_GETMODELREQUEST"]._serialized_end = 492
    _globals["_CLIENTINFO"]._serialized_start = 494
    _globals["_CLIENTINFO"]._serialized_end = 525
    _globals["_REGISTRATIONRESPONSE"]._serialized_start = 527
    _globals["_REGISTRATIONRESPONSE"]._serialized_end = 606
    _globals["_CENTRALSERVER"]._serialized_start = 609
    _globals["_CENTRALSERVER"]._serialized_end = 844
# @@protoc_insertion_point(module_scope)
