# ══════════════════════════════════════════════════════════════════════════════
# Endpoints-Only Evaluation Configuration
#
# Minimal evaluation for fast experiments.
# Only evaluate at the very beginning and end of the experiment.
#
# ══════════════════════════════════════════════════════════════════════════════

# NOTE: Check constructor signature for complete parameter list, defaults, types, and docs.
_target_: src.flora.utils.EvaluationTriggers

# ─────────────────────────────────────────
experiment_start: true # Evaluate at experiment start (baseline)
# experiment_start: false  # Skip initial evaluation

# ─────────────────────────────────────────
experiment_end: true # Evaluate at experiment end (final result)
# experiment_end: false    # Skip final evaluation

# ─────────────────────────────────────────
pre_aggregation: false # Don't evaluate before aggregation
# pre_aggregation: true    # Evaluate before every aggregation
# pre_aggregation:         # Selective pre-aggregation evaluation
#   every: 2               # Before every 2nd aggregation
#   at: [0, 1, 5, 10]      # Before specific aggregations

# ─────────────────────────────────────────
post_aggregation: false # Don't evaluate after aggregation
# post_aggregation: true   # Evaluate after aggregation (standard FL)
# post_aggregation:        # Custom evaluation schedule
#   every: 2               # After every 2nd aggregation
#   at: [0, 1, 5, 10]      # After specific aggregations
