# ══════════════════════════════════════════════════════════════════════════════
# Default Algorithm Configuration
#
# Base template for federated learning algorithms.
# Must be a subclass of src.flora.algorithms.BaseAlgorithm.
# ══════════════════════════════════════════════════════════════════════════════

_target_: ??? # Algorithm implementation class

# ─────────────────────────────────────────
# Training Parameters
# ─────────────────────────────────────────
local_lr: ??? # Local learning rate for client training
max_epochs_per_round: ??? # Maximum training epochs per round
