# ══════════════════════════════════════════════════════════════════════════════
# DiLoCo Algorithm Configuration
#
# Distributed Local SGD with compression.
# Distributed optimizer coordination on server side.
# ══════════════════════════════════════════════════════════════════════════════

_target_: src.flora.algorithms.DiLoCo

outer_lr: 0.7 # Learning rate for server-side outer optimizer
outer_momentum: 0.9 # Momentum coefficient for server-side outer optimizer
