# ------------------------------------------------------------------------------
# DiLoCo Algorithm Configuration
#
# Distributed Local SGD with compression - distributed optimizer on server
# ------------------------------------------------------------------------------

defaults:
  - base

# Dotpath to class implementation
_target_: src.flora.algorithms.DiLoCoNew

# Defaults
outer_lr: 0.7 # Learning rate for server-side outer optimizer
outer_momentum: 0.9 # Momentum coefficient for server-side outer optimizer
