# ══════════════════════════════════════════════════════════════════════════════
# Ditto Algorithm Configuration
#
# Personalized federated learning with fairness constraints.
# Balances global model performance with local personalization.
# ══════════════════════════════════════════════════════════════════════════════

_target_: src.flora.algorithms.Ditto

global_lr: 0.01 # Learning rate for global model updates
ditto_lambda: 0.1 # Regularization coefficient for personalization vs global trade-off
