# ================================================================================
# Ditto Algorithm Configuration
#
# Personalized federated learning with fairness constraints.
# Balances global model performance with local personalization.
# ================================================================================

defaults:
  - base
  - _self_

# NOTE: Check constructor signature for complete parameter list, defaults, types, and docs.
_target_: src.omnifed.algorithm.Ditto

global_lr: 0.01 # Learning rate for global model updates
ditto_lambda: 0.1 # Regularization coefficient for personalization vs global trade-off
