# ================================================================================
# FedAvg Algorithm Configuration
#
# The original federated learning algorithm.
# Simple average of all client model updates.
# ================================================================================

defaults:
  - base
  - _self_

# NOTE: Check constructor signature for complete parameter list, defaults, types, and docs.
_target_: src.flora.algorithm.FedAvg
