# ══════════════════════════════════════════════════════════════════════════════
# FedAvg Algorithm Configuration
#
# The original federated learning algorithm.
# Simple average of all client model updates.
# ══════════════════════════════════════════════════════════════════════════════

_target_: src.flora.algorithms.FedAvg
