# ------------------------------------------------------------------------------
# FedAvg Algorithm Configuration
#
# Federated Averaging - the baseline federated learning algorithm
# ------------------------------------------------------------------------------

defaults:
  - base

# Dotpath to class implementation
_target_: src.flora.algorithms.FedAvg
# FedAvg has no additional parameters beyond the base algorithm
