# ══════════════════════════════════════════════════════════════════════════════
# FedBN Algorithm Configuration
#
# Federated learning with Batch Normalization.
# Keeps batch norm layers local, aggregates other parameters.
# ══════════════════════════════════════════════════════════════════════════════

_target_: src.flora.algorithms.FedBN
