# ================================================================================
# FedBN Algorithm Configuration
#
# Federated learning with Batch Normalization.
# Keeps batch norm layers local, aggregates other parameters.
# ================================================================================

defaults:
    - base
    - _self_

# NOTE: Check constructor signature for complete parameter list, defaults, types, and docs.
_target_: src.flora.algorithm.FedBN
