# ══════════════════════════════════════════════════════════════════════════════
# FedDyn Algorithm Configuration
#
# Dynamic regularization via correction vectors.
# Handles data heterogeneity with adaptive penalties.
# ══════════════════════════════════════════════════════════════════════════════

_target_: src.flora.algorithms.FedDyn

alpha: 0.1 # Controls strength of correction vector regularization
