# ══════════════════════════════════════════════════════════════════════════════
# FedDyn Algorithm Configuration
#
# Dynamic regularization via correction vectors.
# Handles data heterogeneity with adaptive penalties.
# ══════════════════════════════════════════════════════════════════════════════

defaults:
    - base
    - _self_

# NOTE: Check constructor signature for complete parameter list, defaults, types, and docs.
_target_: src.flora.algorithm.FedDyn

alpha: 0.1 # Controls strength of correction vector regularization
