# ------------------------------------------------------------------------------
# FedMom Algorithm Configuration
#
# Federated Momentum - server-side momentum with velocity buffers
# ------------------------------------------------------------------------------

defaults:
  - base

# Dotpath to class implementation
_target_: src.flora.algorithms.FedMomNew

# Defaults
momentum: 0.9 # Momentum coefficient for server-side velocity buffer
