# ================================================================================
# FedMom Algorithm Configuration
#
# Federated learning with momentum.
# Server-side momentum with velocity buffers.
# ================================================================================

defaults:
    - base
    - _self_

# NOTE: Check constructor signature for complete parameter list, defaults, types, and docs.
_target_: src.flora.algorithm.FedMom

momentum: 0.9 # Momentum coefficient for server-side velocity buffer
