# ══════════════════════════════════════════════════════════════════════════════
# FedMom Algorithm Configuration
#
# Federated learning with momentum.
# Server-side momentum with velocity buffers.
# ══════════════════════════════════════════════════════════════════════════════

_target_: src.flora.algorithms.FedMom

momentum: 0.9 # Momentum coefficient for server-side velocity buffer
