# ══════════════════════════════════════════════════════════════════════════════
# FedNova Algorithm Configuration
#
# Normalized federated averaging.
# Normalizes updates by local steps to handle client heterogeneity.
# ══════════════════════════════════════════════════════════════════════════════

_target_: src.flora.algorithms.FedNova

weight_decay: 0.0 # L2 regularization strength for local training
