# ------------------------------------------------------------------------------
# FedNova Algorithm Configuration
#
# FedNova - normalizes updates by local steps to handle client heterogeneity
# ------------------------------------------------------------------------------

defaults:
  - base

# Dotpath to class implementation
_target_: src.flora.algorithms.FedNovaNew

# Defaults
weight_decay: 0.0 # L2 regularization strength for local training
