# ================================================================================
# FedProx Algorithm Configuration
#
# FedProx adds a proximal term to stabilize training in heterogeneous environments.
# Prevents clients from deviating too far from the global model.
# ================================================================================

defaults:
    - base
    - _self_

# NOTE: Check constructor signature for complete parameter list, defaults, types, and docs.
_target_: src.flora.algorithm.FedProx

mu: 0.01 # Proximal term coefficient - controls deviation penalty from global model
