# ══════════════════════════════════════════════════════════════════════════════
# FedProx Algorithm Configuration
#
# FedProx adds a proximal term to stabilize training in heterogeneous environments.
# Prevents clients from deviating too far from the global model.
# ══════════════════════════════════════════════════════════════════════════════

_target_: src.flora.algorithms.FedProx

mu: 0.01 # Proximal term coefficient - controls deviation penalty from global model
