# ══════════════════════════════════════════════════════════════════════════════
# MOON Algorithm Configuration
#
# Model-Contrastive Federated Learning.
# Uses contrastive learning to prevent forgetting of global knowledge.
# ══════════════════════════════════════════════════════════════════════════════

_target_: src.flora.algorithms.MOON

mu: 1.0 # Contrastive loss weight coefficient
temperature: 0.5 # Temperature parameter for softmax in contrastive loss
num_prev_models: 1 # Number of previous global models to maintain for contrastive learning
