# ══════════════════════════════════════════════════════════════════════════════
# MOON Algorithm Configuration
#
# Model-Contrastive Federated Learning.
# Uses contrastive learning to prevent forgetting of global knowledge.
# ══════════════════════════════════════════════════════════════════════════════

defaults:
    - base
    - _self_

# NOTE: Check constructor signature for complete parameter list, defaults, types, and docs.
_target_: src.flora.algorithm.MOON

mu: 1.0 # Contrastive loss weight coefficient
temperature: 0.5 # Temperature parameter for softmax in contrastive loss
num_prev_models: 1 # Number of previous global models to maintain for contrastive learning
