# ------------------------------------------------------------------------------
# SCAFFOLD Algorithm Configuration
#
# SCAFFOLD uses control variates to address client drift in federated learning
# ------------------------------------------------------------------------------

defaults:
  - base

# Dotpath to class implementation
_target_: src.flora.algorithms.Scaffold
# SCAFFOLD has no additional parameters beyond the base algorithm
