# ================================================================================
# SCAFFOLD Algorithm Configuration
#
# SCAFFOLD uses control variates to address client drift in federated learning.
# Maintains control variables to correct for heterogeneous data distributions.
# ================================================================================

defaults:
    - base
    - _self_

# NOTE: Check constructor signature for complete parameter list, defaults, types, and docs.
_target_: src.flora.algorithm.Scaffold
