# ══════════════════════════════════════════════════════════════════════════════
# Base Schedules Configuration
#
# Standard federated learning execution schedule with sensible defaults
# for both aggregation and evaluation timing.
#
# This config provides a working schedule, unlike other base.yaml files.
# You can use this directly or override the aggregation/evaluation components.
# ══════════════════════════════════════════════════════════════════════════════

defaults:
  - aggregation: round_end
  - evaluation: pre_and_post_sync

_target_: src.flora.algorithms.ExecutionSchedules
