# ══════════════════════════════════════════════════════════════════════════════
# Default Schedules Configuration
#
# Standard federated learning execution schedule combining sensible defaults
# for both aggregation and evaluation timing.
# ══════════════════════════════════════════════════════════════════════════════

defaults:
  - aggregation: round_end
  - evaluation: post_agg

# NOTE: Check constructor signature for complete parameter list, defaults, types, and docs.
_target_: src.flora.algorithms.ExecutionSchedules
