# ================================================================================
# VGG Model Family Test Configuration
# Tests various VGG model variants (VGG11, VGG16, VGG19) with batch normalization.
# Demonstrates different VGG architectures with optional pre-trained weights.
# ================================================================================

defaults:
  - base # Base framework configuration
  - override topology: centralized # see ./conf/topology/centralized.yaml
  - override algorithm: fedavg # see ./conf/algorithm/fedavg.yaml
  # NOTE1: In this example, we define the model directly in this file.
  # NOTE2: Alternatively, create configs in `./conf/model/` and use the defaults override
  # - override model: my_model
  - override datamodule: mnist # see ./conf/datamodule/mnist.yaml
  - _self_ # Everything below is merged on top of the above defaults

# ─────────────────────────────────── Topology Overrides
topology:
  num_clients: 3
  local_comm:
    _target_: src.flora.communicator.TorchDistCommunicator
    # master_addr: 127.0.0.1 # Default
    master_port: 29500
  overrides:
    0: # Rank 0 (server) - disable training by setting train dataloader to null
      datamodule:
        train: null

# ─────────────────────────────────── Algorithm Overrides
algorithm:
  local_lr: 0.01
  max_epochs_per_round: 4

# ─────────────────────────────────── Model Configuration
model:
  _target_: torchvision.models.vgg11
  # _target_: torchvision.models.vgg16
  # _target_: torchvision.models.vgg16_bn
  # _target_: torchvision.models.vgg19
  num_classes: 10
  progress: true
  # weights: null  # Random initialization
  # weights: "IMAGENET1K_V1"  # ImageNet pre-trained

# ─────────────────────────────────── DataModule Overrides
datamodule:
  train:
    batch_size: 128
  eval:
    batch_size: 128

# ─────────────────────────────────── Engine Parameters
global_rounds: 3 # see ./conf/base.yaml for all options
