defaults:
  - model: simple_cnn
  - data: mnist
  - topology: centralized
  - _self_

# ───────────── Model Config

model: # overrides the default simple_cnn model
  backbone:
    in_channels: 1 # e.g. MNIST has 1 channel
  head:
    num_classes: 10 # 10 digits

# ───────────── Data Config

data: # overrides the default mnist datamodule
  train:
    batch_size: 16
  val:
    batch_size: 16

# ───────────── Topology and Communication Config

topology: # overrides the default centralized topology
  num_clients: 2 # 2 clients + 1 server = 3 total nodes

comm: ??? # Mandatory marker; composer must override this value

# ───────────── FL Algorithm Config

algo:
  _target_: src.flora.algorithms.FedAvgNew
  max_epochs: 1
  lr: 0.01

# ───────────── FL Engine Config

global_rounds: 3
