# ------------------------------------------------------------------------------
# FLORA Test Configuration – MNIST with Centralized Topology + gRPC Communication
#
# This configuration file extends the base MNIST test setup by specifying the
# centralized topology with gRPC-based communicator for federated learning.
# ------------------------------------------------------------------------------

defaults:
  - test_mnist_base
  - topology: centralized
  - _self_

# ───────────── Topology Config

topology:
  num_clients: 2 # 2 clients + 1 server = 3 total nodes
  local_comm:
    _target_: src.flora.communicator.GrpcCommunicator
