# ================================================================================
# Caltech-256 Test Configuration
# Tests Caltech-256 dataset using FedAvg centralized setup with ResNet50.
# Uses RGB images with 257 object categories (256 + clutter).
# ================================================================================

defaults:
  - base # Base framework configuration
  - override topology: centralized # see ./conf/topology/centralized.yaml
  - override algorithm: fedavg # see ./conf/algorithm/fedavg.yaml
  - override model: resnet50 # see ./conf/model/resnet50.yaml
  - override datamodule: caltech256 # see ./conf/datamodule/caltech256.yaml
  - _self_

# ─────────────────────────────────── Topology Overrides
topology:
  num_clients: 3
  local_comm:
    _target_: src.flora.communicator.TorchDistCommunicator
    # master_addr: 127.0.0.1 # Default
    master_port: 29500
  overrides:
    0: # Rank 0 (server) - disable training by setting train dataloader to null
      datamodule:
        train: null

# ─────────────────────────────────── Algorithm Overrides
algorithm:
  local_lr: 0.001
  max_epochs_per_round: 4

# ─────────────────────────────────── Model Overrides
model:
  num_classes: 257 # 256 object classes + 1 clutter class

# ─────────────────────────────────── DataModule Overrides
datamodule:
  train:
    batch_size: 128
  eval:
    batch_size: 128

# ─────────────────────────────────── Engine Parameters
global_rounds: 3 # see ./conf/base.yaml for all options
