# ------------------------------------------------------------------------------
# FLORA Test Configuration – MNIST with Multi-Group Topology + gRPC Communication
#
# This configuration file extends the base MNIST test setup by specifying the
# multi-group topology for cross-institutional federated learning with gRPC
# coordination between groups.
# ------------------------------------------------------------------------------

defaults:
  - base_mnist_fedavg
  - topology: multigroup
  - _self_

# ───────────── Topology Overrides

topology:
  groups:
    - _target_: src.flora.topology.CentralizedTopology
      num_clients: 2 # Group A: 2 clients + 1 server
      local_comm:
        _target_: src.flora.communicator.TorchDistCommunicator
        master_port: "29500"
    - _target_: src.flora.topology.CentralizedTopology
      num_clients: 2 # Group B: 2 clients + 1 server
      local_comm:
        _target_: src.flora.communicator.TorchDistCommunicator
        master_port: "29501"
  global_comm:
    _target_: src.flora.communicator.GrpcCommunicator
