defaults:
  - _self_
  - model: simple_cnn
  - data: mnist
  - topology: centralized

model: # overrides the default simple_cnn model
  backbone:
    in_channels: 1 # e.g. MNIST has 1 channel
  head:
    num_classes: 10 # 10 digits

data: # overrides the default mnist datamodule
  train:
    batch_size: 16
  val:
    batch_size: 16

comm:
  _target_: src.flora.communicator.TorchDistCommunicator
  master_addr: "127.0.0.1"
  master_port: "29500"
  backend: "gloo"
  timeout: 20

algo:
  _target_: src.flora.algorithms.FedAvgNew
  lr: 0.01

topology: # overrides the default centralized topology
  num_nodes: 3

# ───────────── Engine Config

global_rounds: 3
