# ================================================================================
# MobileNet Model Family Test Configuration
# Tests MobileNet model variants optimized for mobile and edge deployment.
# Demonstrates efficient CNN architectures (MobileNetV3 Large/Small).
# ================================================================================

defaults:
  - base # Base framework configuration
  - override topology: centralized # see ./conf/topology/centralized.yaml
  - override algorithm: fedavg # see ./conf/algorithm/fedavg.yaml
  # NOTE1: In this example, we define the model directly in this file.
  # NOTE2: Alternatively, create configs in `./conf/model/` and use the defaults override
  # - override model: my_model
  - override datamodule: mnist # see ./conf/datamodule/mnist.yaml
  - _self_ # Everything below is merged on top of the above defaults

# ─────────────────────────────────── Topology Overrides
topology:
  num_clients: 3
  local_comm:
    _target_: src.omnifed.communicator.TorchDistCommunicator
    # master_addr: 127.0.0.1 # Default
    master_port: 29500
  overrides:
    0: # Rank 0 (server) - disable training by setting train dataloader to null
      datamodule:
        train: null

# ─────────────────────────────────── Algorithm Overrides
algorithm:
  local_lr: 0.01
  max_epochs_per_round: 4

# ─────────────────────────────────── Model Configuration
model:
  # _target_: torchvision.models.mobilenet_v3_small
  _target_: torchvision.models.mobilenet_v3_large
  num_classes: 10
  progress: true
  # weights: null  # Random initialization
  # weights: "IMAGENET1K_V1"  # ImageNet pre-trained (original)
  # weights: "IMAGENET1K_V2"  # ImageNet pre-trained (improved)

# ─────────────────────────────────── DataModule Overrides
datamodule:
  train:
    batch_size: 128
  eval:
    batch_size: 128

# ─────────────────────────────────── Engine Parameters
global_rounds: 3 # see ./conf/base.yaml for all options
