# ------------------------------------------------------------------------------
# FLORA Test Configuration – MNIST with Centralized Topology + TorchDist Communication
#
# This file extends the base MNIST test configuration by specifying the
# centralized topology with Torch Distributed (TorchDist) communication.
# ------------------------------------------------------------------------------

defaults:
  - base_mnist_fedavg
  - topology: centralized

# ───────────── Algorithm Overrides

algorithm:
  max_epochs_per_round: 2

# ───────────── Topology Overrides

topology:
  num_clients: 2 # 2 clients + 1 server = 3 total nodes
  local_comm:
    _target_: src.flora.communicator.TorchDistCommunicator
    # master_addr: "127.0.0.1"
    # master_port: "29500"
    # backend: "gloo"

# ───────────── Engine Overrides

global_rounds: 2
