# ------------------------------------------------------------------------------
# FLORA Test Configuration – MNIST with gRPC Communication
#
# This configuration file extends the base MNIST test setup by specifying the
# gRPC-based communicator for federated learning communication.
# ------------------------------------------------------------------------------

defaults:
  - test_mnist_base
  - _self_

comm:
  _target_: src.flora.communicator.GrpcCommunicator
