# ================================================================================
# MNIST FedAvg Hierarchical Experiment with Mixed Communication
# Complete configuration for MNIST experiments with FedAvg algorithm.
# Uses hierarchical topology with 2 groups of 3 clients each (6 total).
# Mixed communication: gRPC for global, TorchDist for local.
# Runs for 3 global rounds with 4 local epochs per round.
# ================================================================================

defaults:
  - base # Base framework configuration
  - override model: resnet18 # see ./conf/model/simple_cnn.yaml
  - override datamodule: cifar10 # see ./conf/datamodule/mnist.yaml
  - override topology: hierarchical # see ./conf/topology/hierarchical.yaml
  - override algorithm: fedavg # see ./conf/algorithm/fedavg.yaml
  - _self_ # Everything below is merged on top of the above defaults

# ─────────────────────────────────── Hierarchical Topology Overrides
topology:
  global_comm: # Inter-group Communication
    _target_: src.flora.communicator.GrpcCommunicator
    # master_addr: 127.0.0.1 # Default
    master_port: 50051
  groups:
    # ──────────────────────────────── Group 1
    - _target_: src.flora.topology.CentralizedTopology
      num_clients: 3
      local_comm:
        _target_: src.flora.communicator.TorchDistCommunicator
        # master_addr: 127.0.0.1 # Default
        master_port: 29500
      overrides:
        0: # Rank 0 (server) - disable training by setting train dataloader to null
          datamodule:
            train: null

    # ──────────────────────────────── Group 2
    - _target_: src.flora.topology.CentralizedTopology
      num_clients: 3
      local_comm:
        _target_: src.flora.communicator.TorchDistCommunicator
        # master_addr: 127.0.0.1 # Default
        master_port: 29501
      overrides:
        0: # Rank 0 (server) - disable training by setting train dataloader to null
          datamodule:
            train: null

# ─────────────────────────────────── FedAvg Overrides
algorithm:
  local_lr: 0.01
  max_epochs_per_round: 10

# ─────────────────────────────────── SimpleCNN Overrides
model:
  num_classes: 10

# ─────────────────────────────────── MNIST DataModule Overrides
datamodule:
  train:
    batch_size: 128
  eval:
    batch_size: 128

# ─────────────────────────────────── Engine Parameters
global_rounds: 5 # see ./conf/base.yaml for all options
