# ══════════════════════════════════════════════════════════════════════════════
# MNIST FedAvg MultiGroup Experiment with Mixed Communication
#
# Complete configuration for MNIST experiments with FedAvg algorithm.
# Uses multigroup topology with 2 groups of 2 clients each (4 total clients).
# Mixed communication: gRPC for global, TorchDist for local.
# ══════════════════════════════════════════════════════════════════════════════

defaults:
  - base # Base framework configuration
  - override topology: multigroup_mixed # MultiGroup FL topology with mixed communication
  - override algorithm: fedavg # FedAvg algorithm
  - override model: simple_cnn # Simple CNN for image classification
  - override datamodule: mnist # MNIST dataset
  - _self_ # Override with local settings

# ─────────────────────────────────────────
# Experiment Parameters

global_rounds: 2

# ─────────────────────────────────────────
# Component Overrides

topology:
  groups:
    - num_clients: 2 # Group 1: 2 clients
      local_comm:
        _target_: src.flora.communicator.TorchDistCommunicator
    # ───────────────────────────
    - num_clients: 2 # Group 2: 2 clients
      local_comm:
        _target_: src.flora.communicator.TorchDistCommunicator

algorithm:
  local_lr: 0.01
  max_epochs_per_round: 2

model:
  backbone:
    in_channels: 1 # MNIST grayscale images
  head:
    num_classes: 10 # 10 digit classes

datamodule:
  train:
    batch_size: 16
  eval:
    batch_size: 16
