# ================================================================================
# Fashion-MNIST Test Configuration
# Tests Fashion-MNIST dataset using FedAvg centralized setup with SimpleCNN.
# Uses grayscale images with 10 clothing categories.
# ================================================================================

defaults:
  - base # Base framework configuration
  - override topology: centralized # see ./conf/topology/centralized.yaml
  - override algorithm: fedavg # see ./conf/algorithm/fedavg.yaml
  - override model: simple_cnn # see ./conf/model/simple_cnn.yaml
  - override datamodule: fashion_mnist # see ./conf/datamodule/fashion_mnist.yaml
  - _self_

# ─────────────────────────────────── Topology Overrides
topology:
  num_clients: 3
  local_comm:
    _target_: src.flora.communicator.TorchDistCommunicator
    # master_addr: 127.0.0.1 # Default
    master_port: 29500
  overrides:
    0: # Rank 0 (server) - disable training by setting train dataloader to null
      datamodule:
        train: null

# ─────────────────────────────────── Algorithm Overrides
algorithm:
  local_lr: 0.001
  max_epochs_per_round: 4

# ─────────────────────────────────── Model Overrides
model:
  backbone:
    in_channels: 1 # Fashion-MNIST grayscale
  head:
    num_classes: 10 # 10 clothing classes

# ─────────────────────────────────── DataModule Overrides
datamodule:
  train:
    batch_size: 128
  eval:
    batch_size: 128

# ─────────────────────────────────── Engine Parameters
global_rounds: 3 # see ./conf/base.yaml for all options
