# Test configuration for MNIST without evaluation data
# This demonstrates optional eval dataset functionality

defaults:
  - test_mnist_base
  - topology: centralized
  - _self_

# Override to remove eval dataset
data:
  # Only provide train data, no eval
  train:
    batch_size: 16
  eval: null

# Use smaller topology for faster testing
topology:
  num_clients: 2
  local_comm:
    _target_: src.flora.communicator.TorchDistCommunicator

# Shorter experiment for testing
global_rounds: 1

algorithm:
  max_epochs_per_round: 1
  eval_schedule:
    experiment_start: false
    experiment_end: false