# ------------------------------------------------------------------------------
# FLORA Test Configuration – Base MNIST Setup
#
# This configuration file provides the baseline settings for testing a simple
# Convolutional Neural Network (CNN) on the MNIST dataset. It includes default
# settings for the model, dataset configuration, FL topology, and FL algorithm.
#
# This file is intended to be extended by other configurations which override
# the communication settings.
# ------------------------------------------------------------------------------

defaults:
  - base
  - algorithm: fedavg
  - model: simple_cnn
  - data: mnist

# ───────────── FL Algorithm Config

algorithm:
  local_lr: 0.01
  max_epochs_per_round: 2

# ───────────── Model Config

model: # overrides the default simple_cnn model
  backbone:
    in_channels: 1 # e.g. MNIST has 1 channel
  head:
    num_classes: 10 # 10 digits

# ───────────── Data Config

data: # overrides the default mnist datamodule
  train:
    batch_size: 16
  eval:
    batch_size: 16

# ───────────── FL Engine Config

global_rounds: 2
