# ================================================================================
# MNIST FedAvg Hierarchical Experiment with Mixed Communication
#
# Complete configuration for MNIST experiments with FedAvg algorithm.
# Uses hierarchical topology with 2 groups of 3 clients each (6 total).
# Mixed communication: gRPC for global, TorchDist for local.
# Runs for 3 global rounds with 4 local epochs per round.
# ================================================================================

defaults:
  - base # Base framework configuration
  - override model: simple_cnn # reference template for custom PyTorch models.
  - override datamodule: mnist # reference template for custom datasets.
  - override topology: hierarchical # using hierarchical topology template
  - override algorithm: fedavg # using FedAvg algorithm template
  - _self_ # Everything below is merged on top of the above defaults

# ─────────────────────────────────── Hierarchical Topology Overrides
topology:
  global_comm: # Inter-group Communication
    _target_: src.flora.communicator.GrpcCommunicator
    # master_addr: 127.0.0.1 # Default
    master_port: 50051
    # ... see class docs/constructor for more options
  groups:
    # ──────────────────────────────── Group 1
    - _target_: src.flora.topology.CentralizedTopology
      num_clients: 3
      local_comm:
        _target_: src.flora.communicator.TorchDistCommunicator
        # master_addr: 127.0.0.1 # Default
        master_port: 29500
        # ... see class docs/constructor for more options
    # ──────────────────────────────── Group 2
    - _target_: src.flora.topology.CentralizedTopology
      num_clients: 3
      local_comm:
        _target_: src.flora.communicator.TorchDistCommunicator
        # master_addr: 127.0.0.1 # Default
        master_port: 29501
        # ... see class docs/constructor for more options

# ─────────────────────────────────── FedAvg Algorithm Overrides
algorithm: # see ./conf/algorithm/fedavg.yaml for all options
  local_lr: 0.01
  max_epochs_per_round: 4

# ─────────────────────────────────── SimpleCNN Overrides
model: # see ./conf/model/simple_cnn.yaml for all options
  backbone:
    in_channels: 1 # MNIST grayscale
  head:
    num_classes: 10 # MNIST digits

# ─────────────────────────────────── MNIST DataModule Overrides
datamodule: # see ./conf/datamodule/mnist.yaml for all options
  train:
    batch_size: 128
  eval:
    batch_size: 128

# ─────────────────────────────────── Engine Parameters
# see ./conf/base.yaml for all options

global_rounds: 3
