# ------------------------------------------------------------------------------
# FLORA Test Configuration – MNIST with Torch Distributed Communication
#
# This file extends the base MNIST test configuration by overriding the
# communication backend to use the Torch Distributed (TorchDist) protocol.
# ------------------------------------------------------------------------------

defaults:
  - test_mnist_base
  - _self_

comm:
  _target_: src.flora.communicator.TorchDistCommunicator
  # master_addr: "127.0.0.1"
  # master_port: "29500"
  # backend: "gloo"
