# ================================================================================
# Epoch-End Aggregation Configuration
#
# High-frequency aggregation pattern.
# Aggregate model updates at the end of each epoch during local training.
# ================================================================================

# NOTE: Check constructor signature for complete parameter list, defaults, types, and docs.
_target_: src.flora.algorithm.AggregationTriggers

# ─────────────────────────────────────────
round_end:
    _target_: src.flora.algorithm._schedules.Trigger
    enabled: false

# ─────────────────────────────────────────
epoch_end: # Aggregate after each epoch
    _target_: src.flora.algorithm._schedules.Trigger
    enabled: true
    every: 1
    # at: [1, 3, 5, 10] # Aggregate at specific epochs

# ─────────────────────────────────────────
batch_end:
    _target_: src.flora.algorithm._schedules.Trigger
    enabled: false
