# ══════════════════════════════════════════════════════════════════════════════
# Default Model Configuration
#
# Base template for neural network models.
# Must be a torch.nn.Module.
# ══════════════════════════════════════════════════════════════════════════════

_target_: ??? # Model implementation class
