# ./conf/model/simple_cnn.yaml

# Defines a generic, reusable CNN architecture blueprint.

_target_: src.flora.models.ComposableModel

backbone:
  _target_: src.flora.models.SimpleCNNBackbone
  in_channels: ??? # Mandatory marker; composer must override this value
  conv_channels: [32, 64]
  kernel_sizes: 3
  paddings: 1

head:
  _target_: src.flora.models.ClassificationHead
  in_channels: 64
  num_classes: ??? # Mandatory marker; composer must override this value
