# ================================================================================
# Base Evaluation Configuration
#
# Template for evaluation timing configurations.
# Works with src.flora.algorithm.EvaluationTriggers.
# Compose this base in specific evaluation configs (like standard.yaml) with "- base" in their defaults list.
# Override the evaluation timing parameters marked with ???.
# ================================================================================

_target_: src.flora.algorithm.EvaluationTriggers

# Required evaluation timing parameters - override in specific configs:
experiment_start: ???
experiment_end: ???

pre_aggregation: ???
# pre_aggregation:         # Selective pre-aggregation evaluation
#   every: 2               # Before every 2nd aggregation
#   at: [0, 1, 5, 10]      # Before specific aggregations

post_aggregation: ???
# post_aggregation:        # Selective post-aggregation evaluation
#   every: 2               # After every 2nd aggregation
#   at: [0, 1, 5, 10]      # After specific aggregations

# Examples for specific configs:
# experiment_start: true/false
# pre_aggregation: true/false or {every: 2} or {at: [0, 1, 5, 10]}
# post_aggregation: true/false or {every: 2} or {at: [0, 1, 5, 10]}
