# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

import parameter_server_pb2 as parameter__server__pb2

GRPC_GENERATED_VERSION = "1.73.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in parameter_server_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ParameterServerStub(object):
    """Service definition for parameter server"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendUpdate = channel.unary_unary(
            "/parameter_server.ParameterServer/SendUpdate",
            request_serializer=parameter__server__pb2.ModelUpdate.SerializeToString,
            response_deserializer=parameter__server__pb2.UpdateResponse.FromString,
            _registered_method=True,
        )
        self.GetAveragedModel = channel.unary_unary(
            "/parameter_server.ParameterServer/GetAveragedModel",
            request_serializer=parameter__server__pb2.GetModelRequest.SerializeToString,
            response_deserializer=parameter__server__pb2.ModelParameters.FromString,
            _registered_method=True,
        )
        self.RegisterClient = channel.unary_unary(
            "/parameter_server.ParameterServer/RegisterClient",
            request_serializer=parameter__server__pb2.ClientInfo.SerializeToString,
            response_deserializer=parameter__server__pb2.RegistrationResponse.FromString,
            _registered_method=True,
        )


class ParameterServerServicer(object):
    """Service definition for parameter server"""

    def SendUpdate(self, request, context):
        """Send model updates to server"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetAveragedModel(self, request, context):
        """Get averaged model parameters from server"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RegisterClient(self, request, context):
        """Register client with server"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ParameterServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "SendUpdate": grpc.unary_unary_rpc_method_handler(
            servicer.SendUpdate,
            request_deserializer=parameter__server__pb2.ModelUpdate.FromString,
            response_serializer=parameter__server__pb2.UpdateResponse.SerializeToString,
        ),
        "GetAveragedModel": grpc.unary_unary_rpc_method_handler(
            servicer.GetAveragedModel,
            request_deserializer=parameter__server__pb2.GetModelRequest.FromString,
            response_serializer=parameter__server__pb2.ModelParameters.SerializeToString,
        ),
        "RegisterClient": grpc.unary_unary_rpc_method_handler(
            servicer.RegisterClient,
            request_deserializer=parameter__server__pb2.ClientInfo.FromString,
            response_serializer=parameter__server__pb2.RegistrationResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "parameter_server.ParameterServer", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "parameter_server.ParameterServer", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class ParameterServer(object):
    """Service definition for parameter server"""

    @staticmethod
    def SendUpdate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/parameter_server.ParameterServer/SendUpdate",
            parameter__server__pb2.ModelUpdate.SerializeToString,
            parameter__server__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetAveragedModel(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/parameter_server.ParameterServer/GetAveragedModel",
            parameter__server__pb2.GetModelRequest.SerializeToString,
            parameter__server__pb2.ModelParameters.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RegisterClient(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/parameter_server.ParameterServer/RegisterClient",
            parameter__server__pb2.ClientInfo.SerializeToString,
            parameter__server__pb2.RegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
