# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: parameter_server.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 0, "", "parameter_server.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x16parameter_server.proto\x12\x10parameter_server"i\n\x0bModelUpdate\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x14\n\x0cround_number\x18\x02 \x01(\x05\x12\x31\n\x06layers\x18\x03 \x03(\x0b\x32!.parameter_server.LayerParameters"p\n\x0fLayerParameters\x12\x12\n\nlayer_name\x18\x01 \x01(\t\x12\x0f\n\x07weights\x18\x02 \x03(\x02\x12\x0e\n\x06\x62iases\x18\x03 \x03(\x02\x12\x14\n\x0cweight_shape\x18\x04 \x03(\x05\x12\x12\n\nbias_shape\x18\x05 \x03(\x05"l\n\x0fModelParameters\x12\x14\n\x0cround_number\x18\x01 \x01(\x05\x12\x31\n\x06layers\x18\x02 \x03(\x0b\x32!.parameter_server.LayerParameters\x12\x10\n\x08is_ready\x18\x03 \x01(\x08"h\n\x0eUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1a\n\x12\x63lients_registered\x18\x03 \x01(\x05\x12\x18\n\x10updates_received\x18\x04 \x01(\x05":\n\x0fGetModelRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x14\n\x0cround_number\x18\x02 \x01(\x05"\x1f\n\nClientInfo\x12\x11\n\tclient_id\x18\x01 \x01(\t"O\n\x14RegistrationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rtotal_clients\x18\x03 \x01(\x05\x32\x92\x02\n\x0fParameterServer\x12M\n\nSendUpdate\x12\x1d.parameter_server.ModelUpdate\x1a .parameter_server.UpdateResponse\x12X\n\x10GetAveragedModel\x12!.parameter_server.GetModelRequest\x1a!.parameter_server.ModelParameters\x12V\n\x0eRegisterClient\x12\x1c.parameter_server.ClientInfo\x1a&.parameter_server.RegistrationResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "parameter_server_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_MODELUPDATE"]._serialized_start = 44
    _globals["_MODELUPDATE"]._serialized_end = 149
    _globals["_LAYERPARAMETERS"]._serialized_start = 151
    _globals["_LAYERPARAMETERS"]._serialized_end = 263
    _globals["_MODELPARAMETERS"]._serialized_start = 265
    _globals["_MODELPARAMETERS"]._serialized_end = 373
    _globals["_UPDATERESPONSE"]._serialized_start = 375
    _globals["_UPDATERESPONSE"]._serialized_end = 479
    _globals["_GETMODELREQUEST"]._serialized_start = 481
    _globals["_GETMODELREQUEST"]._serialized_end = 539
    _globals["_CLIENTINFO"]._serialized_start = 541
    _globals["_CLIENTINFO"]._serialized_end = 572
    _globals["_REGISTRATIONRESPONSE"]._serialized_start = 574
    _globals["_REGISTRATIONRESPONSE"]._serialized_end = 653
    _globals["_PARAMETERSERVER"]._serialized_start = 656
    _globals["_PARAMETERSERVER"]._serialized_end = 930
# @@protoc_insertion_point(module_scope)
