# ================================================================================
# Base DataModule Configuration
#
# Template for data module configurations with train/eval data loaders.
# Works with src.flora.data.DataModule.
# Compose this base in specific datamodule configs (like mnist.yaml) with "- base" in their defaults list.
# Override defaults and add the dataset-specific parameters your chosen datasets need.
# ================================================================================

defaults:
  - dataloader@train # Use dataloader config group and assign to 'train' field
  - dataloader@eval # Use dataloader config group and assign to 'eval' field
  - _self_

_target_: src.flora.data.DataModule

# Default data loader settings:
train:
  shuffle: true # Training data should be shuffled

  # shuffle: false # Fixes ValueError('sampler option is mutually exclusive with shuffle')
  # # For debugging purposes, we sample a small subset of the dataset.
  # sampler:
  #   _target_: torch.utils.data.RandomSampler
  #   data_source: ${..dataset} # Re-use dataset from the datamodule (datamodule.train.dataset)
  #   replacement: false
  #   num_samples: 5000

eval:
  shuffle: false # Evaluation data should not be shuffled


  # # For debugging purposes, we sample a small subset of the dataset.
  # sampler:
  #   _target_: torch.utils.data.RandomSampler
  #   data_source: ${..dataset} # Re-use dataset from the datamodule (datamodule.eval.dataset)
  #   replacement: false
  #   num_samples: 1000
