# ══════════════════════════════════════════════════════════════════════════════
# Default DataModule Configuration
#
# Base template for FLORA DataModule with train/eval data loaders.
# Must be src.flora.data.DataModule.
# ══════════════════════════════════════════════════════════════════════════════

defaults:
  - dataloader@train
  - dataloader@eval

# NOTE: Check constructor signature for complete parameter list, defaults, types, and docs.
_target_: src.flora.data.DataModule

# ─────────────────────────────────────────
# Training Data
# ─────────────────────────────────────────
train:
  shuffle: true # Training data should be shuffled

# ─────────────────────────────────────────
# Evaluation Data
# ─────────────────────────────────────────
eval:
  shuffle: false # Evaluation data should not be shuffled
