# ══════════════════════════════════════════════════════════════════════════════
# Fashion-MNIST Dataset Configuration
#
# Configures FLORA DataModule for Fashion-MNIST clothing classification.
# Uses torchvision dataset with standard normalization values for Fashion-MNIST.
#
# Docs:
# - https://pytorch.org/vision/stable/generated/torchvision.datasets.FashionMNIST.html
# - https://github.com/zalandoresearch/fashion-mnist
# ══════════════════════════════════════════════════════════════════════════════

defaults:
  - base
  - _self_

# ─────────────────────────────────────────
# Training Data
# ─────────────────────────────────────────
train:
  dataset:
    _target_: torchvision.datasets.FashionMNIST
    root: ${oc.env:FLORA_DATA_DIR,/tmp}/fashion-mnist
    train: true  # Use training set
    # target_transform: null  # Optional transform for targets
    download: true
    transform:
      _target_: torchvision.transforms.Compose
      transforms:
        - _target_: torchvision.transforms.ToTensor
        - _target_: torchvision.transforms.RandomHorizontalFlip
          p: 0.5
        - _target_: torchvision.transforms.Normalize
          mean: [0.2859]  # Fashion-MNIST specific mean (corrected)
          std: [0.3530]   # Fashion-MNIST specific std

# ─────────────────────────────────────────
# Evaluation Data
# ─────────────────────────────────────────
eval:
  dataset:
    _target_: torchvision.datasets.FashionMNIST
    root: ${oc.env:FLORA_DATA_DIR,/tmp}/fashion-mnist
    train: false  # Use test set
    # target_transform: null  # Optional transform for targets
    download: true
    transform:
      _target_: torchvision.transforms.Compose
      transforms:
        - _target_: torchvision.transforms.ToTensor
        - _target_: torchvision.transforms.Normalize
          mean: [0.2859]  # Fashion-MNIST specific mean (corrected)
          std: [0.3530]   # Fashion-MNIST specific std