# ================================================================================
# MNIST Dataset Configuration
#
# Configures FLUX DataModule for MNIST handwritten digits.
# Uses torchvision dataset with standard normalization.
#
# Docs:
# - https://pytorch.org/vision/stable/generated/torchvision.datasets.MNIST.html
# ================================================================================

defaults:
  - base
  - _self_

# ─────────────────────────────────────────
# Training Data
# ─────────────────────────────────────────
train:
  dataset:
    _target_: torchvision.datasets.MNIST
    root: ${oc.env:FLUX_DATA_DIR,/tmp}/torchvision-mnist
    train: true
    download: true
    transform:
      _target_: torchvision.transforms.Compose
      transforms:
        - _target_: torchvision.transforms.ToTensor
        - _target_: torchvision.transforms.Normalize
          mean: [0.1307]
          std: [0.3081]

# ─────────────────────────────────────────
# Evaluation Data
# ─────────────────────────────────────────
eval:
  dataset:
    _target_: torchvision.datasets.MNIST
    root: ${oc.env:FLUX_DATA_DIR,/tmp}/torchvision-mnist
    train: false
    download: true
    transform:
      _target_: torchvision.transforms.Compose
      transforms:
        - _target_: torchvision.transforms.ToTensor
        - _target_: torchvision.transforms.Normalize
          mean: [0.1307]
          std: [0.3081]
