# ══════════════════════════════════════════════════════════════════════════════
# MNIST Dataset Configuration
#
# Configures FLORA DataModule for MNIST handwritten digits.
# Uses torchvision dataset with standard normalization.
#
# Docs: https://pytorch.org/vision/stable/generated/torchvision.datasets.MNIST.html
# ══════════════════════════════════════════════════════════════════════════════

_target_: src.flora.data.DataModule

# ─────────────────────────────────────────
# Training Data
train:
  dataset:
    _target_: torchvision.datasets.MNIST
    root: /tmp/torchvision-mnist
    train: true
    download: true
    transform:
      _target_: torchvision.transforms.Compose
      transforms:
        - _target_: torchvision.transforms.ToTensor
        - _target_: torchvision.transforms.Normalize
          mean: [0.1307]
          std: [0.3081]
  num_workers: 2
  pin_memory: true
  persistent_workers: true
  shuffle: true

# ─────────────────────────────────────────
# Evaluation Data
eval:
  dataset:
    _target_: torchvision.datasets.MNIST
    root: /tmp/torchvision-mnist
    train: false
    download: true
    transform:
      _target_: torchvision.transforms.Compose
      transforms:
        - _target_: torchvision.transforms.ToTensor
        - _target_: torchvision.transforms.Normalize
          mean: [0.1307]
          std: [0.3081]
  num_workers: 2
  pin_memory: true
  persistent_workers: true
  shuffle: false
