# ══════════════════════════════════════════════════════════════════════════════
# Default Topology Configuration
#
# Base template for network topologies.
# Must be a subclass of src.flora.topology.BaseTopology.
# ══════════════════════════════════════════════════════════════════════════════

_target_: ??? # Topology implementation class
